add core.gen.tr to community/commercial-support
NixOS/nixos-homepage pull request #1027
Opened 2023-03-28 17:38 UTC by evrim

Let me know if there is a typo, have no means of linting ;)

best,
evrim.

2023-03-28 23:58 UTC, figsoda commented on community/commercial-support.toml
> +locations = ["Remote" "Istanbul"]
```suggestion
locations = ["Remote", "Istanbul"]
```

2023-03-29 00:30 UTC, evrim commented on community/commercial-support.toml
> +locations = ["Remote" "Istanbul"]
OK, added the missing comma, thnx!

2023-03-29 07:59 UTC, garbas requested changes
https://core.gen.tr url is not working for me.

2023-03-29 08:06 UTC, evrim commented
ping @garbas

2023-04-04 11:25 UTC, garbas commented
Hi @evrim!

I'm a little hesitant to merge this PR. Here are the reasons:
- The url points to a blog
- No where on the website there is a mention that there you are providing Nix services.
- There is only one blog post regarding Nix

The page commercial provides should include links with commercial providers for Nix users and I don't think your URL meets the criteria. I will bring this up at the next Marketing meeting. We should also write down the criteria.

I'll be back with the answer in 10 days.

2023-11-08 21:25 UTC, tomberek commented
> page commercial provides should include links with commercial providers for Nix users and I don't think your URL meets the criteria. I will bring this up at the next Marketing meeting. We should

I agree with @garbas 's assessment.

2023-11-09 18:50 UTC, evrim commented
I am afraid I am not here to satisfy your egos. If you change the rules after the game starts, nobody will have any trust in the rules or the system. The time will come that this record will be used against who do just that. Close the issue if you are trying to mess around with me and my enterprise.

best,
evrim.

2023-11-10 22:00 UTC, tomberek commented
The commercial support page is not meant to be a blog aggregator. The proposed link is a blog and it is not clear how someone looking for commercial support should contact you. We'd be happy to include or showcase specific Nix content via announcements or cross-posting. Closing. Feel free to reopen if the situation changes.

2023-11-10 22:00 UTC, closed without merging

2023-11-11 23:35 UTC, evrim commented
Thnx for the confirmation.

2024-08-22 09:44 UTC, evrim commented
re-open, re-eval request, check out https://www.core.gen.tr

2024-08-22 09:44 UTC, evrim commented
ping @tomberek @garbas