add redirect to catch removed Nix manual page (profiles)
NixOS/nixos-homepage pull request #1137
Opened 2023-10-23 03:39 UTC by fricklerhandwerk

depends on https://github.com/NixOS/nix/pull/9209

2023-10-30 22:21 UTC, garbas requested changes

2023-11-02 02:04 UTC, fricklerhandwerk commented on netlify.toml
> +  status = 301
```suggestion
  status = 302
```

2023-11-02 11:38 UTC, garbas approved these changes

2023-11-02 11:39 UTC, garbas commented
@fricklerhandwerk I'll let you merge it when https://github.com/NixOS/nix/pull/9209 is merged.

2024-04-02 07:51 UTC, closed without merging