Astro/download page [WIP]
NixOS/nixos-homepage pull request #1164
Opened 2023-11-23 17:25 UTC by djacu

2023-11-25 02:04 UTC, djacu commented
@garbas @thilobillerbeck This is ready for review. It works as far as I can tell.

One thing I didn't realize was how the tabs for the different section changed when the screen is less wide. I didn't account for this when designing the components. It can probably be fixed but I haven't figured out how to do it yet.

You can see the comparison below. The old way hides the original tabs and unhides these header tags that are used to collapse the content after. The way I have it now is that the just changes the grid layout.

What do you think? Do we want to match the old way?
If so, and either of you want to give it a try, please feel free.
I've been working on this for 3 days and need a break.

<details><summary>OLD</summary>

![image](https://github.com/NixOS/nixos-homepage/assets/7043297/baae6c53-d6d9-4dde-8d74-b147e0c544dd)
</details>

<details><summary>NEW</summary>

![image](https://github.com/NixOS/nixos-homepage/assets/7043297/248153b7-4d1c-438e-aded-08fe894c2f22)
</details>

2023-11-30 01:36 UTC, thilobillerbeck requested changes
Looks good, thanks for your work! There are some small things I marked with a comment but nothing too big.

One thing this implementation clearly leaves open is how we deal with hard coded links to things like NixOS releases, I think it would be better if there would be a place to just swap verison numbers on release and all URLS adapt.

Apart from that I like the mobile UI. It is (against what we planned) not a 1:1 port of the original design but it's okay for me. In the future we maybe could add some kind of dropdown at the top with a heading like `Choose platform` to save on mobile screen space, but it's okay for now. :)

2023-12-07 07:02 UTC, djacu commented on src/components/pages/download/components/recommended.astro
Done!

2023-12-07 07:02 UTC, djacu commented on src/components/pages/download/components/DownloadButtonAndSHA.astro
Done!

2023-12-07 07:06 UTC, djacu commented
@thilobillerbeck all changes resolved
See https://github.com/NixOS/nixos-homepage/pull/1164/commits/2a2b082048cb8fd1b109de65e24c4eb328520725 for modifications to the Button class to allow for optional SHA arguments.
See https://github.com/NixOS/nixos-homepage/pull/1164/commits/86e3ee3801ca73138b6b48f8a2ee475048342d8e for the new Tag class.

2023-12-07 14:19 UTC, thilobillerbeck approved these changes

2023-12-07 14:20 UTC, thilobillerbeck commented
looks good, the Button on the `/learn` page seems to be broken but this is a fix we can incorporate shortly before publishing the site. Thx for the work.

2023-12-07 14:21 UTC, merged