Small buttons update
NixOS/nixos-homepage pull request #1608
Opened 2024-12-14 11:28 UTC by SvMak

- use cva(class-variance-authority) for variants;
- made all buttons full rounded.

2024-12-24 23:59 UTC, thilobillerbeck requested changes
Introducing `class-variance-authority` is definitely a good idea, though I have two small nitpicks. :)

2024-12-24 23:59 UTC, thilobillerbeck commented on src/components/ui/Button.astro
> +  'font-bold text-white drop-shadow transition-colors rounded-full text-center',
This is an interesting design change, though I'm not really a fan of it, this comes especially into play when seeing how buttons behave inside cards as seen on the learn site. The fully rounded corners do not really seem to fit into the more boxy card shape, while the old design aligns more with its parent design and at least in my opinion looks more coherent.

2024-12-24 23:59 UTC, thilobillerbeck commented on src/components/ui/Button.astro
> +        green: 'bg-nix-green hover:bg-nix-green-hover',
In my testing I couldn't really tell how the hover state applied, am I missing something or is it just to subtile? I'd guess the mentioned colors may need to be defined first. :D

2024-12-31 17:12 UTC, thilobillerbeck commented
This is almost right. Though the original design had `rounded-2xl`  for `lg*` buttons and `rounded-3xl` for `sm*` buttons. This was not by accident and I'd appreciate if we keep it that way. We could discuss if we unify the 3xl buttons into a 2xl border radius, but especially in combination with other elements, 2xl makes more sense.

Sorry to bother you again. If I had the permission to push to this PR, I'd just fix it myself. :/

2025-01-07 20:20 UTC, SvMak commented
Sorry for late (((

2025-01-13 17:14 UTC, thilobillerbeck approved these changes

2025-01-13 17:14 UTC, merged

2025-01-13 17:14 UTC, thilobillerbeck commented
no problem :D looks alright now, thx for contributing :)