donate.html: initial structure and text
NixOS/nixos-homepage pull request #588
Opened 2020-09-28 15:25 UTC by garbas

Design: [NixOS_DonatePage_D1.pdf](https://github.com/NixOS/nixos-homepage/files/5293312/NixOS_DonatePage_D1.pdf)

## TODO

- [ ] vertical "NixOS Foundation" logo, needs some inkscape work (@samueldr)
- [ ] _diagonal_ light blue background for stores section (@samueldr)
- [ ] image of some fictional character wearing NixOS t-shirt (designer via @garbas)
- [ ] add both stores to the store section (@garbas)
- [ ] prepare text for open collective (@garbas)
- [ ] 3 columns for sponsors in Acknowledgements section, also size of images should be the same (@garbas)

2020-10-05 08:11 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/marketing-team-meeting-minutes-14/9304/1

2020-10-13 18:03 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/hello-tux-shirts/7979/15

2020-10-14 22:16 UTC, samueldr commented
I'm left with the "Foundation" logo to handle.

Though I see you've made pretty good use of text replacement to use the existing logo+logotype, but with a text-based "Foundation" word.

What is desired for the "Foundation" word? I like the idea of having a thinner "Foundation" word under the NixOS word, like currently implented:

![image](https://user-images.githubusercontent.com/132835/96051283-2ae53d00-0e49-11eb-89a3-d3873eafb37f.png)

Maybe [*Vegur ExtraLight*](https://www.fontsquirrel.com/fonts/vegur) rather than the currently inherited font.

Any other thoughts?

2020-10-15 07:43 UTC, garbas commented
> Though I see you've made pretty good use of text replacement to use the existing logo+logotype, but with a text-based "Foundation" word.
> 

Yeah I just want to move forward, but in case you don't have time I just implemented a CSS based version that looks similar.

> What is desired for the "Foundation" word? I like the idea of having a thinner "Foundation" word under the NixOS word, like currently implented:
> 
> ![image](https://user-images.githubusercontent.com/132835/96051283-2ae53d00-0e49-11eb-89a3-d3873eafb37f.png)
> 
> Maybe [_Vegur ExtraLight_](https://www.fontsquirrel.com/fonts/vegur) rather than the currently inherited font.
> 
> Any other thoughts?

Yes, use the same font as the NixOS text but lighter. `Vegur ExtraLight` sounds about right.

2020-10-20 02:05 UTC, samueldr commented
:bangbang: The foundation logo has been implemented in #589

2020-10-20 19:15 UTC, garbas commented
I merge #589 and master ... we have only few things left to finish this PR.

2020-10-20 19:21 UTC, samueldr commented
> > > icons for teams (need export from the design @garbas)
> > 
> > 
> > Are the icons from the PDF not okay? If they are I can try extracting them, chances are it'll work just fine since it's not a complicated bit in the PDF.
> 
> Yes the icons are good from the PDF just I don't know how to extract them.

Good, I'll handle *exporting* them at the very least.

The gist of it is importing the PDF in inkscape, it will generally handle things fine. Though sometimes it requires a bit of cleanup for things like reducing the amount of points by "simplifying" the paths, and such, so the files end up smaller. Ideally, one would also try to "pixel-snap" lines so they don't end up fuzzy if shown at 1:1 scale.

2020-10-21 21:20 UTC, samueldr commented
The graphical elements have been extracted, only. They are "face12"'d so they can be coloured with svg.less. If you need more help for them just ask.

They're all exported with 138x138px bounding boxes, so you can apply them to element "centered and contained" and they will be the right scale comparative to each other.

2020-10-22 16:01 UTC, davidak requested changes
overall it looks very good. well done!

2020-10-22 18:33 UTC, garbas commented on donate.tt
> +              <img src="[% root %]logo/fastly.png" alt="Fastly" />
@davidak how did you get to the glitch?

2020-10-22 18:44 UTC, merged

2020-10-22 19:57 UTC, davidak commented on donate.tt
> +              <img src="[% root %]logo/fastly.png" alt="Fastly" />
open in browser? i mean that the white space around the fastly is not a rectangle like the other, but the corners are cut out, like you see in the screenshot

2020-11-05 16:51 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/tweag-nix-dev-update-4/9862/1