download.tt: KDE → Plasma
NixOS/nixos-homepage pull request #614
Opened 2020-10-09 22:05 UTC by samueldr

And one instance where it was simply dropped. Being irrelevant.

cc @worldofpeace; fixes #613

2020-10-09 22:41 UTC, worldofpeace approved these changes
Thanks

2020-10-10 00:09 UTC, davidak requested changes
what about this?

2020-10-10 00:09 UTC, davidak commented on download.tt
> +            installer</strong> as well as <strong>Plasma 5</strong> and
```suggestion
            installer</strong> as well as <strong>Plasma Desktop</strong> and
```

2020-10-10 00:09 UTC, davidak commented on download.tt
> +        <p>VirtualBox image includes includes <strong>Plasma 5</strong> as
```suggestion
        <p>VirtualBox image includes the <strong>Plasma Desktop</strong> as
```

2020-10-10 01:02 UTC, samueldr commented
I don't really know about "Plasma Desktop";

 * https://kde.org/plasma-desktop

> Plasma is a Desktop
> 
> Use Plasma to surf the web; keep in touch with colleagues, friends and family; manage your files, enjoy music and videos; and get creative and productive at work. Do it all in a beautiful environment that adapts to your needs, and with the safety, privacy-protection and peace of mind that the best Free Open Source Software has to offer.

It's unclear what is the preferred way to refer to Plasma.

2020-10-12 12:17 UTC, garbas requested changes

2020-10-12 12:17 UTC, garbas commented on download.tt
> +        <p>VirtualBox image includes the <strong>Plasma Desktop</strong> as
```suggestion
        <p>VirtualBox image includes the <strong>Plasma Desktop</strong> (was KDE) as
```
I think a lot of linux users are unaware that Plasma Desktop is what KDE used to be.

2020-10-12 12:18 UTC, garbas approved these changes

2020-10-12 12:49 UTC, merged